# schema.py
"""
Database Schema - Pydantic models matching schema/posts.schema.sql

This module defines Pydantic models that exactly match the database schema
defined in schema/posts.schema.sql. DO NOT modify the SQL schema file.
All schema changes must be reflected here from the SQL source of truth.

Models:
- PostSchema: posts table
- FileSchema: files table
- TagSchema: tags table
- CategorySchema: categories table
- PostTagSchema: post_tags junction table
- PostCategorySchema: post_categories junction table
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional
from datetime import datetime
from enum import Enum


# ===========================
# ENUMS (matching SQL ENUMs)
# ===========================

class PostStatusEnum(str, Enum):
    """Post status matching post_status_enum in SQL"""
    PUBLIC = "public"
    PRIVATE = "private"
    FOLLOWER = "follower"


class UsersAuthProvider(str, Enum):
    """User auth provider matching users_auth_provider in SQL"""
    APP = "app"
    FACEBOOK = "facebook"
    GOOGLE = "google"
    GITHUB = "github"
    KAKAO = "kakao"
    NAVER = "naver"
    APPLE = "apple"
    TWITTER = "twitter"
    LINKEDIN = "linkedin"
    MICROSOFT = "microsoft"
    YAHOO = "yahoo"


# ===========================
# MAIN SCHEMAS
# ===========================

class PostSchema(BaseModel):
    """
    Post schema matching posts table in schema/posts.schema.sql

    Supports hierarchical structure for posts and comments:
    - Post (root): group_id = self, parent_id = NULL, level = 0
    - Comment: group_id = root post, parent_id = post/comment, level = 1+

    Table structure:
    - seq: BIGINT GENERATED ALWAYS AS IDENTITY (auto-increment)
    - id: BIGINT GENERATED BY DEFAULT AS IDENTITY (snowflake)
    - group_id: BIGINT (root post ID, self for root posts)
    - level: INT DEFAULT 0 (depth: 0=post, 1+=comment)
    - parent_id: BIGINT NULL (NULL for posts, parent ID for comments)
    - priority: INT DEFAULT 100 (ordering)
    - slug: VARCHAR(255) NOT NULL
    - title: VARCHAR(255) NOT NULL
    - content: TEXT
    - category_id: BIGINT NULL
    - user_id: BIGINT NOT NULL
    - description: TEXT
    - status: post_status_enum DEFAULT 'public'
    - created_at, updated_at, deleted_at: TIMESTAMP
    """
    model_config = ConfigDict(from_attributes=True)

    # Identity
    id: Optional[int] = Field(default=None, description="Post/comment snowflake ID")

    # Hierarchy (for posts and comments)
    group_id: Optional[int] = Field(default=None, description="Root post ID (self for root posts)")
    level: int = Field(default=0, description="Depth: 0=post, 1=comment, 2+=nested reply")
    parent_id: Optional[int] = Field(default=None, description="Parent ID (NULL for posts, post/comment ID for replies)")
    priority: int = Field(default=100, description="Display order priority")

    # Content
    slug: str = Field(max_length=255, description="URL-friendly slug")
    title: str = Field(max_length=255, description="Post/comment title")
    content: Optional[str] = Field(default=None, description="Full content in markdown")
    description: Optional[str] = Field(default=None, description="Post description/summary")

    # Relations
    category_id: Optional[int] = Field(default=None, description="Primary category snowflake ID")
    user_id: int = Field(description="Author user ID")

    # Status
    status: PostStatusEnum = Field(default=PostStatusEnum.PUBLIC, description="Visibility status")

    # SEO fields
    meta_title: Optional[str] = Field(default=None, max_length=70, description="SEO title for search results")
    meta_description: Optional[str] = Field(default=None, max_length=170, description="SEO description for search results")
    og_image_url: Optional[str] = Field(default=None, description="Open Graph image URL for social sharing")
    og_image_alt: Optional[str] = Field(default=None, max_length=125, description="Open Graph image alt text")

    # Timestamps
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
    deleted_at: Optional[datetime] = Field(default=None, description="Soft delete timestamp")


class FileSchema(BaseModel):
    """
    File schema matching files table in schema/posts.schema.sql

    Table structure:
    - id: BIGINT GENERATED BY DEFAULT AS IDENTITY
    - user_id: BIGINT
    - post_id: BIGINT
    - content_type: VARCHAR(100)
    - ext: VARCHAR(30)
    - original_filename: VARCHAR(255) NOT NULL
    - stored_name: VARCHAR(255) NOT NULL
    - s3_key: TEXT NULL (S3 key path)
    - stored_uri: TEXT NOT NULL (Full CDN URL)
    - file_size: INTEGER
    - is_thumbnail: BOOLEAN DEFAULT FALSE
    - created_at: TIMESTAMP
    - updated_at: TIMESTAMP
    - deleted_at: TIMESTAMP

    Maps to MCPFileInfo:
    - original_filename -> original_filename
    - stored_name -> stored_name (slug-based)
    - s3_key -> s3_key (e.g., "4/tech/ai/slug/slug.png")
    - stored_uri -> s3_url (full CDN URL)
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[int] = Field(default=None, description="Auto-generated file ID")
    user_id: Optional[int] = Field(default=None, description="User ID who uploaded the file")
    post_id: Optional[int] = Field(default=None, description="Associated post ID")
    content_type: Optional[str] = Field(default=None, max_length=100, description="MIME type")
    ext: Optional[str] = Field(default=None, max_length=30, description="File extension")
    original_filename: str = Field(max_length=255, description="Original filename from local filesystem")
    stored_name: str = Field(max_length=255, description="Slug-based filename for storage")
    s3_key: Optional[str] = Field(default=None, description="S3 key path (e.g., user_id/category/.../slug/filename)")
    stored_uri: str = Field(description="Full CDN URL where file is stored")
    file_size: Optional[int] = Field(default=None, description="File size in bytes")
    is_thumbnail: bool = Field(default=False, description="Whether this is a thumbnail image")
    created_at: Optional[datetime] = Field(default=None, description="Upload timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
    deleted_at: Optional[datetime] = Field(default=None, description="Soft delete timestamp")


class TagSchema(BaseModel):
    """
    Tag schema matching tags table in schema/posts.schema.sql

    Table structure:
    - id: BIGSERIAL
    - name: VARCHAR(50) UNIQUE NOT NULL
    - created_at: TIMESTAMP
    - updated_at: TIMESTAMP
    - deleted_at: TIMESTAMP
    """
    model_config = ConfigDict(from_attributes=True)

    id: Optional[int] = Field(default=None, description="Auto-generated tag ID")
    name: str = Field(max_length=50, description="Tag name (unique)")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
    deleted_at: Optional[datetime] = Field(default=None, description="Soft delete timestamp")


class CategorySchema(BaseModel):
    """
    Category schema matching categories table in schema/posts.schema.sql

    Table structure:
    - seq: BIGINT GENERATED ALWAYS AS IDENTITY (auto-increment, unique)
    - id: BIGINT GENERATED BY DEFAULT AS IDENTITY (can be manually set)
    - group_id: BIGINT NULL (root category ID, same as id for root categories)
    - level: INT DEFAULT 0 NOT NULL (hierarchy level, 0 = root)
    - priority: INT DEFAULT 100 NOT NULL (display order priority)
    - parent_id: BIGINT NULL (parent category ID, NULL for root)
    - user_id: BIGINT NOT NULL (user who created this category)
    - title: VARCHAR(100) NOT NULL UNIQUE (category name, unique constraint)
    - created_at, updated_at, deleted_at: TIMESTAMP
    """
    model_config = ConfigDict(from_attributes=True)

    seq: Optional[int] = Field(default=None, description="Auto-generated sequential number (unique)")
    id: Optional[int] = Field(default=None, description="Category ID (auto-generated or manual)")
    group_id: Optional[int] = Field(default=None, description="Root category ID (self-reference for root)")
    level: int = Field(default=0, description="Hierarchy level (0 = root, 1+ = children)")
    priority: int = Field(default=100, description="Display order priority")
    parent_id: Optional[int] = Field(default=None, description="Parent category ID (NULL for root)")
    user_id: int = Field(description="User ID who created this category")
    title: str = Field(max_length=100, description="Category name (unique)")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
    deleted_at: Optional[datetime] = Field(default=None, description="Soft delete timestamp")


# ===========================
# JUNCTION TABLE SCHEMAS
# ===========================

class PostTagSchema(BaseModel):
    """
    Post-Tag relationship schema matching post_tags table

    Table structure:
    - post_id: BIGINT NOT NULL
    - tag_name: VARCHAR(50) NOT NULL
    - created_at: TIMESTAMP
    - updated_at: TIMESTAMP
    - deleted_at: TIMESTAMP
    """
    model_config = ConfigDict(from_attributes=True)

    post_id: int = Field(description="Post ID")
    tag_name: str = Field(max_length=50, description="Tag name")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
    deleted_at: Optional[datetime] = Field(default=None, description="Soft delete timestamp")


class PostCategorySchema(BaseModel):
    """
    Post-Category relationship schema matching post_categories table

    Table structure:
    - post_id: BIGINT NOT NULL
    - category_id: BIGINT NOT NULL
    - created_at: TIMESTAMP
    - updated_at: TIMESTAMP
    - deleted_at: TIMESTAMP
    """
    model_config = ConfigDict(from_attributes=True)

    post_id: int = Field(description="Post ID")
    category_id: int = Field(description="Category ID")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Last update timestamp")
    deleted_at: Optional[datetime] = Field(default=None, description="Soft delete timestamp")


# ===========================
# COMPOSITE SCHEMAS FOR AGENTS
# ===========================

class PostWithRelations(BaseModel):
    """
    Composite schema for a post with all its related data.
    Used by agents to work with complete post information.
    """
    model_config = ConfigDict(from_attributes=True)

    # Core post data
    post: PostSchema

    # Related data
    files: List[FileSchema] = Field(default_factory=list, description="Associated files/images")
    tags: List[str] = Field(default_factory=list, description="Tag names")
    categories: List[int] = Field(default_factory=list, description="Category IDs")

    # Computed fields
    thumbnail_file: Optional[FileSchema] = Field(default=None, description="Thumbnail file if exists")
    word_count: Optional[int] = Field(default=None, description="Word count of content")
    reading_time: Optional[int] = Field(default=None, description="Estimated reading time in minutes")


# ===========================
# HELPER FUNCTIONS
# ===========================

def calculate_reading_time(word_count: int, wpm: int = 250) -> int:
    """
    Calculate reading time from word count

    Args:
        word_count: Total word count
        wpm: Words per minute (default: 250)

    Returns:
        Estimated reading time in minutes
    """
    return max(1, round(word_count / wpm))


def get_schema_description(schema: type[BaseModel]) -> str:
    """
    Convert Pydantic schema to LLM-readable string description

    Args:
        schema: Pydantic BaseModel class

    Returns:
        Formatted string describing the schema
    """
    lines = [f"# {schema.__name__}", ""]

    if schema.__doc__:
        lines.append(schema.__doc__.strip())
        lines.append("")

    lines.append("## Fields:")
    lines.append("")

    for name, field in schema.model_fields.items():
        # Extract type
        field_type = field.annotation
        if hasattr(field_type, "__name__"):
            type_str = field_type.__name__
        else:
            type_str = str(field_type)

        # Required/Optional
        required = "required" if field.is_required() else "optional"

        # Description
        description = field.description or "No description"

        # Default value
        default = ""
        if not field.is_required() and field.default is not None:
            default = f" (default: {field.default})"

        lines.append(f"- **{name}** ({type_str}, {required}){default}")
        lines.append(f"  {description}")
        lines.append("")

    return "\n".join(lines)


# ===========================
# VALIDATION HELPERS
# ===========================

def validate_slug(slug: str) -> bool:
    """
    Validate slug format (alphanumeric and hyphens only)

    Args:
        slug: Slug string to validate

    Returns:
        True if valid, False otherwise
    """
    import re
    return bool(re.match(r'^[a-z0-9-]+$', slug))


def generate_slug_from_title(title: str) -> str:
    """
    Generate URL-friendly slug from title

    Args:
        title: Post title

    Returns:
        URL-friendly slug
    """
    import re
    # Convert to lowercase
    slug = title.lower()
    # Replace spaces and special chars with hyphens
    slug = re.sub(r'[^a-z0-9]+', '-', slug)
    # Remove leading/trailing hyphens
    slug = slug.strip('-')
    # Collapse multiple hyphens
    slug = re.sub(r'-+', '-', slug)
    return slug


# ===========================
# ===========================
# UPLOAD PAYLOAD SCHEMAS
# ===========================

class FileInfo(BaseModel):
    """
    File information for upload payload.
    Contains both original and stored (slug-based) filenames.
    """
    model_config = ConfigDict(from_attributes=True)

    # Original file info
    original_filename: str = Field(description="Original filename from local filesystem")
    local_path: Optional[str] = Field(default=None, description="Local filesystem path")

    # Stored file info (slug-based)
    stored_name: str = Field(description="Slug-based filename for storage")
    s3_key: str = Field(description="Full S3 key path")
    s3_url: str = Field(description="Full S3/CDN URL")

    # File metadata
    content_type: Optional[str] = Field(default=None, description="MIME type (e.g., image/png)")
    ext: Optional[str] = Field(default=None, description="File extension without dot")
    file_size: Optional[int] = Field(default=None, description="File size in bytes")

    # Flags
    is_thumbnail: bool = Field(default=False, description="Whether this is the thumbnail image")


class CategoryInfo(BaseModel):
    """
    Category information for upload operations.
    Used when creating or linking categories in the hierarchy.
    """
    model_config = ConfigDict(from_attributes=True)

    # Category identification
    id: Optional[int] = Field(default=None, description="Category snowflake ID (if known)")
    title: str = Field(description="Category name (e.g., 'technology')")

    # Hierarchy info
    level: int = Field(default=0, description="Hierarchy level (0 = root)")
    parent_id: Optional[int] = Field(default=None, description="Parent category snowflake ID")
    group_id: Optional[int] = Field(default=None, description="Root category snowflake ID")

    # Ownership
    user_id: int = Field(description="User ID who owns this category")


class ArticleMetadata(BaseModel):
    """
    Article metadata extracted from frontmatter and processing.

    Supports hierarchical structure:
    - Post (root): group_id = self, parent_id = NULL, level = 0
    - Comment: group_id = root post, parent_id = post/comment, level = 1+
    """
    model_config = ConfigDict(from_attributes=True)

    # Core identifiers
    title: str = Field(description="Article title")
    slug: str = Field(description="URL-friendly slug")

    # User info
    user_id: int = Field(description="User ID who owns this post")
    username: str = Field(description="Username for URL (@username)")

    # Hierarchy (for posts and comments)
    group_id: Optional[int] = Field(default=None, description="Root post ID (self for root posts, set after creation)")
    level: int = Field(default=0, description="Depth: 0=post, 1=comment, 2+=nested reply")
    parent_id: Optional[int] = Field(default=None, description="Parent ID (NULL for posts, post/comment ID for replies)")
    priority: int = Field(default=100, description="Display order priority")

    # Content metadata
    description: Optional[str] = Field(default=None, description="Article description/summary")
    status: PostStatusEnum = Field(default=PostStatusEnum.PUBLIC, description="Post visibility")
    date: Optional[str] = Field(default=None, description="Publication date from frontmatter")

    # Categories (from folder path)
    categories: List[str] = Field(default_factory=list, description="Category hierarchy names")
    category_ids: List[int] = Field(default_factory=list, description="Resolved category snowflake IDs")
    category_id: Optional[int] = Field(default=None, description="Primary (deepest) category snowflake ID")

    # Tags
    tags: List[str] = Field(default_factory=list, description="Article tags")

    # Computed metadata
    word_count: Optional[int] = Field(default=None, description="Word count of content")
    reading_time: Optional[int] = Field(default=None, description="Estimated reading time in minutes")

    # SEO fields
    meta_title: Optional[str] = Field(default=None, max_length=70, description="SEO title for search results")
    meta_description: Optional[str] = Field(default=None, max_length=170, description="SEO description for search results")
    og_image_url: Optional[str] = Field(default=None, description="Open Graph image URL for social sharing")
    og_image_alt: Optional[str] = Field(default=None, max_length=125, description="Open Graph image alt text")



class UploadPayload(BaseModel):
    """
    Complete payload for post upload.

    This model contains all information needed to:
    1. Create a post record in the database
    2. Create file records for thumbnail and images
    3. Link post to categories and tags

    Usage:
        payload = UploadPayload(
            metadata=ArticleMetadata(...),
            content="# Markdown content...",
            thumbnail=FileInfo(...),
            images=[FileInfo(...), ...],
        )
    """
    model_config = ConfigDict(from_attributes=True)

    # Article metadata
    metadata: ArticleMetadata = Field(description="Article metadata from frontmatter")

    # Content with CDN URLs (already processed)
    content: str = Field(description="Markdown content with CDN image URLs")

    # Thumbnail (required)
    thumbnail: FileInfo = Field(description="Thumbnail image info")

    # Content images (optional)
    images: List[FileInfo] = Field(default_factory=list, description="Content images")

    # Category hierarchy with full info
    category_hierarchy: List[CategoryInfo] = Field(
        default_factory=list,
        description="Full category hierarchy with snowflake IDs for linking"
    )

    # Generated URLs
    published_url: str = Field(description="Final published URL")

    # Processing info
    source_file: Optional[str] = Field(default=None, description="Original markdown file path")
    processed_at: Optional[datetime] = Field(default=None, description="Processing timestamp")


class UploadResponse(BaseModel):
    """
    Response after successful upload.
    """
    model_config = ConfigDict(from_attributes=True)

    success: bool = Field(description="Whether upload was successful")
    post_id: Optional[int] = Field(default=None, description="Created post ID")
    file_ids: List[int] = Field(default_factory=list, description="Created file record IDs")
    category_ids: List[int] = Field(default_factory=list, description="Linked category IDs")
    tag_ids: List[int] = Field(default_factory=list, description="Created/linked tag IDs")
    published_url: Optional[str] = Field(default=None, description="Final published URL")
    error: Optional[str] = Field(default=None, description="Error message if failed")


# Backward compatibility aliases
MCPFileInfo = FileInfo
MCPCategoryInfo = CategoryInfo
MCPArticleMetadata = ArticleMetadata
MCPUploadPayload = UploadPayload
MCPUploadResponse = UploadResponse


# ===========================
# SCHEMA REFERENCE
# ===========================

# This module matches schema/posts.schema.sql exactly.
# Do NOT modify the SQL file - it is the source of truth.
# Any schema changes must originate from the SQL file and be reflected here.
