# database schema
-- ===========================
-- USERS TABLE
-- ===========================
CREATE TYPE if not exists users_auth_provider AS ENUM (
    'app', 
    'facebook', 
    'google',
    'github',
    'kakao',
    'naver',
    'apple',
    'twitter',
    'linkedin',
    'microsoft',
    'yahoo',
);

drop table if exists users;
CREATE TABLE if not exists users (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, 
    id              BIGSERIAL PRIMARY KEY,
    username        VARCHAR(50) UNIQUE,
    email           VARCHAR(255) UNIQUE,
    password_hash   VARCHAR(255), -- nullable
    provider        users_auth_provider NOT NULL DEFAULT 'app', -- ex: google, github, apple
    provider_id     VARCHAR(255) UNIQUE, -- external id from oauth
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

insert into users (username, email)
VALUES ('darkowlrising', 'darkowlrising@gmail.com');
insert into users (username, email)
VALUES ('taeklim', 'tio.taek.lim@gmail.com');


-- ===========================
-- POSTS TABLE
-- ===========================
CREATE TYPE if not exists post_status_enum AS ENUM ('public', 'private', 'follower');
drop table if exists posts;
CREATE TABLE posts (
    seq             int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,     
    -- id              BIGSERIAL PRIMARY KEY,
    -- id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    group_id        BIGINT,                         -- 루트 글 ID (root면 자기 자신)
    level           INT DEFAULT 0,                  -- 깊이 (root = 0)
    parent_id       BIGINT NULL,                    -- 부모 글 ID
    FOREIGN KEY (parent_id) REFERENCES posts(id) on delete cascade,
    -- --
    priority        INT NOT NULL DEFAULT 100,
    -- reply_count     INT DEFAULT 0,                  -- 자식 글 수
    slug            VARCHAR(255) NOT NULL,
    title           VARCHAR(255) NOT NULL,
    content         TEXT,
    category_id     BIGINT NULL,
    user_id         BIGINT NOT NULL,
    description     TEXT DEFAULT NULL,
    -- SEO fields
    meta_title      VARCHAR(70) DEFAULT NULL,
    meta_description VARCHAR(170) DEFAULT NULL,
    og_image_url    TEXT DEFAULT NULL,
    og_image_alt    VARCHAR(125) DEFAULT NULL,
    -- --
    status          post_status_enum NOT NULL DEFAULT 'public',    
    -- --
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id)
);

--> just in case to update colums
-- ALTER TABLE posts ADD COLUMN meta_title VARCHAR(70);
-- ALTER TABLE posts ADD COLUMN meta_description VARCHAR(170);
-- ALTER TABLE posts ADD COLUMN og_image_url TEXT;
-- ALTER TABLE posts ADD COLUMN og_image_alt VARCHAR(125);



-- ===========================
-- categories TABLE
-- ===========================
-- CREATE TABLE categories (
--     id          BIGSERIAL PRIMARY KEY,
--     name        VARCHAR(100) NOT NULL,
--     parent_id   BIGINT REFERENCES categories(id) ON DELETE CASCADE,
--     root_id     BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
--     level       INT NOT NULL DEFAULT 0,
--     UNIQUE(name, parent_id)
-- );

-- drop table if exists categories;
-- CREATE TABLE if not exists categories (
--     id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     name        VARCHAR(100) NOT NULL, --UNIQUE,
--     parent_id   BIGINT NOT NULL,
--     root_id     BIGINT NOT NULL,
--     level       INT NOT NULL DEFAULT 0,
--     created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     deleted_at      TIMESTAMP DEFAULT NULL
-- );

CREATE TABLE if not exists categories ( 
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, 
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, 
    group_id int8 NULL, 
    "level" int4 DEFAULT 0 NOT NULL, 
    priority int4 DEFAULT 100 NOT NULL, 
    parent_id int8 NULL, 
    user_id int8 NOT NULL, 
    title varchar(100) NOT NULL, 
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL, 
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL, 
    deleted_at timestamp NULL, CONSTRAINT categories_pkey 
    PRIMARY KEY (id), 
    CONSTRAINT categories_seq_key UNIQUE (seq), 
    CONSTRAINT categories_user_title_key UNIQUE (user_id, title), 
    CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id) ON DELETE CASCADE, 
    CONSTRAINT categories_parent_id_fkey1 FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);

-- 인덱스
CREATE INDEX if not exists idx_categories_parent_id ON categories(parent_id);
CREATE INDEX if not exists idx_categories_root_id ON categories(root_id);
CREATE INDEX if not exists idx_categories_level ON categories(level);


-- ===========================
-- FILES TABLE
-- ===========================
-- Maps to MCPFileInfo in schema.py:
--   original_filename: Original filename from local filesystem
--   stored_name: Slug-based filename for storage (e.g., "article-slug.png")
--   s3_key: Full S3 key path (e.g., "4/tech/ai/article-slug/article-slug.png")
--   s3_url: Full CDN URL (stored_uri alias)
--   content_type: MIME type
--   ext: File extension without dot
--   file_size: Size in bytes
--   is_thumbnail: Whether this is the post thumbnail
drop table if exists files;
CREATE TABLE if not exists files (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    post_id         BIGINT,
    content_type    VARCHAR(100),
    ext             VARCHAR(30),
    original_filename   VARCHAR(255) NOT NULL,
    stored_name         VARCHAR(255) NOT NULL,
    s3_key              TEXT NULL,              -- S3 key path (e.g., "user_id/category/.../slug/filename")
    stored_uri          TEXT NOT NULL,          -- Full CDN URL (s3_url)
    file_size           INTEGER,
    is_thumbnail        BOOLEAN DEFAULT FALSE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at          TIMESTAMP DEFAULT NULL,
    UNIQUE(user_id, stored_name)
);

-- ===========================
-- TAGS TABLE
-- ===========================
CREATE TABLE if not exists tags (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, 
    id              BIGSERIAL PRIMARY KEY,
    title           VARCHAR(50) UNIQUE NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL    
);
CREATE INDEX if not exists idx_tags_title ON tags(title);

-- ===========================
-- POST_TAGS (many-to-many)
-- ===========================
drop table if exists post_tags;
CREATE TABLE if not exists post_tags (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, 
    post_id         BIGINT NOT NULL,
    tag_title       VARCHAR(50) UNIQUE NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,    
    PRIMARY KEY (post_id, tag_title)
);

-- ===========================
-- INDEXES
-- ===========================
CREATE INDEX if not exists idx_users_username ON users(username);
CREATE INDEX if not exists idx_users_provider_id ON users(provider_id);
CREATE INDEX if not exists idx_posts_user_id ON posts(user_id);
CREATE INDEX if not exists idx_files_user_id ON files(user_id);
CREATE INDEX if not exists idx_files_post_id ON files(post_id);
CREATE INDEX if not exists idx_post_tags_tag_title ON post_tags(tag_title);
CREATE INDEX if not exists idx_post_tags_post_id ON post_tags(post_id);


-- ===========================
-- post_categories TABLE
-- ===========================
-- CREATE TABLE post_categories (
--     post_id     BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
--     category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
--     PRIMARY KEY (post_id, category_id)
-- );
CREATE TABLE if not exists post_categories (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, 
    post_id     BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,    
    PRIMARY KEY (post_id, category_id)
);

CREATE INDEX if not exists idx_post_categories_category_id ON post_categories(category_id);
CREATE INDEX if not exists idx_post_categories_post_id ON post_categories(post_id);


-- ===========================
-- upsert
-- ===========================

INSERT INTO users (username, email, password_hash)
VALUES ('john', 'john@example.com', 'hashed_pw')
ON CONFLICT (email)
DO UPDATE
SET username = EXCLUDED.username,
    password_hash = EXCLUDED.password_hash,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO users (username, email)
VALUES ('john', 'john@example.com')
ON CONFLICT (email)
DO NOTHING;


-- 복합 인덱스 추가로 성능 극대화
CREATE INDEX IF NOT EXISTS idx_posts_user_deleted_id 
ON posts(user_id, deleted_at, id DESC) 
WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_posts_slug_created 
ON posts(slug, created_at DESC, id DESC) 
WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_files_post_thumbnail 
ON files(post_id, is_thumbnail) 
WHERE deleted_at IS NULL AND is_thumbnail = true;